name: Generate and Push OpenAPI Documentation

on:
  push:
    branches:
      - main
    paths:
      - websiteApi/**
  pull_request:
    branches:
      - main
    paths:
      - websiteApi/**

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.2'

      - name: Install Swagger
        run: go install github.com/swaggo/swag/cmd/swag@latest
        working-directory: websiteApi

      - name: Generate Swagger docs
        run: swag init -g cmd/api/main.go -o docs
        working-directory: websiteApi

      - name: Commit and Push Swagger docs
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/
          if git diff --quiet docs/; then
            echo "No changes in docs/ to commit."
          else
            git commit -m 'Generate and update Swagger docs'
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: websiteApi